name: budz_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  banner_carousel: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

  
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-100.ttf
          weight: 100
        - asset: assets/fonts/Outfit-200.ttf
          weight: 200
        - asset: assets/fonts/Outfit-300.ttf
          weight: 300
        - asset: assets/fonts/Outfit-400.ttf
          weight: 400
        - asset: assets/fonts/Outfit-500.ttf
          weight: 500
        - asset: assets/fonts/Outfit-600.ttf
          weight: 600
        - asset: assets/fonts/Outfit-700.ttf
          weight: 700
        - asset: assets/fonts/Outfit-800.ttf
          weight: 800
        - asset: assets/fonts/Outfit-900.ttf
          weight: 900